export const URL1_CHANGED = 'URL1_CHANGED';
export const URL2_CHANGED = 'URL2_CHANGED';
export const INVALID_URL1 = 'INVALID_URL1';
export const INVALID_URL2 = 'INVALID_URL2';
export const PRODUCT_SPEC_FETCH = 'PRODUCT_SPEC_FETCH';
export const PRODUCT_SPEC_UPDATE = 'PRODUCT_SPEC_UPDATE';